[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "=0.0.1"

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  source = "https://github.com/beyondprotocol/cosmos-sdk.git"
  branch = "Deepcover" 

[[constraint]]
  name = "github.com/spf13/viper"
  version = "=1.0.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.1.0"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "=v0.11.1"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "v0.14.1"

[[override]]
  name = "github.com/tendermint/tendermint"
  source = "https://github.com/beyondprotocol/tendermint.git"
  branch = "DeepcoverNew" 

[[override]]
  name = "github.com/syndtr/goleveldb"
  revision = "c4c61651e9e37fa117f53c5a906d3b63090d8445"

[[override]]
  name = "golang.org/x/sys"
  revision = "4e1fef5609515ec7a2cee7b5de30ba6d9b438cbf"

[[override]]
  name = "google.golang.org/genproto"
  revision = "383e8b2c3b9e36c4076b235b32537292176bae20"

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"

[prune]
 go-tests = true
 unused-packages = true
