[[constraint]]
        name = "github.com/spf13/cobra"
        version = "=0.0.1"

[[constraint]]
        name = "github.com/spf13/viper"
        version = "=1.0.0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "=v0.12.0"

[[constraint]]
        name = "github.com/cosmos/cosmos-sdk"
        source = "https://github.com/beyondprotocol/cosmos-sdk.git"
		version = "0.25.0-rc1"
		
[[override]]
        name = "github.com/golang/protobuf"
        version = "=1.1.0"		
  
[[override]]
  name = "github.com/tendermint/iavl"
  version = "=v0.11.0"

[[override]]
        name = "github.com/tendermint/tendermint"
        version = "=0.25.1-rc0"
  
[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"
  
[prune]
        go-tests = true
        unused-packages = true
